Classroom/Controllers/HelloController.cs
using Microsoft.AspNetCore.Mvc;

namespace Classroom.Controllers
{
    public class HelloController : Controller
    {
        public IActionResult Index()
        {
            if(User.Identity.IsAuthenticated)
            {
                return Redirect("Home/Index");
            }

            return View();

        }


        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Classroom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Classroom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Classroom.styles.css" asp-append-version="true" />
    @RenderSection("CSSSection", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Hello" asp-action="Index">
                    <img src="/images/logo.png" alt="Logo" style="height: 30px; margin-right: 10px;" />
            Classroom
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Classroom/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @RenderSection("CSSSection", required: false)
    <style>
        .avatar{
            background-color: #00712D;
        }
        .avatar-menu ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .avatar-menu li {
            padding: 10px;
        }

        .avatar-menu a {
            text-decoration: none;
            color: black;
        }

        .avatar-menu i {
            margin-right: 10px;
            width: 20px;
        }

    </style>
</head>
<header>
    <div class="top-menu">
        <i class="fas fa-bars menu-icon" id="menu-toggle"></i>
        <a asp-controller="Home" asp-action="Index" style="text-decoration:none"><div class="logo">Classroom</div></a>
        <div class="top-menu-right">
            <i class="fas fa-plus add-icon" id="add-menu-toggle"></i>
            <div class="avatar" id="avatar-toggle"><i class="fas fa-user"></i></div>
        </div>
    </div>
    <div class="avatar-menu" id="avatar-menu">
        <ul>
            <li>
                <i class="fas fa-user" style="color:#00712D"></i>
                <a href="/Identity/Account/Manage">My Profile</a>
            </li>
            <li>
                <i class="fas fa-sign-out-alt" style="color:#00712D"></i>
                <a href="/Identity/Account/Logout">Log out</a>
            </li>
        </ul>
    </div>
    <div class="add-menu" id="add-menu">
        <ul>
            <li><a class="btn" asp-controller="Home" asp-action="JoinClassRoom"><i class="fas fa-plus" style="color:#00712D"></i> Join Class</a></li>
            <li><a class="btn" asp-controller="Home" asp-action="CreateClassRoom"><i class="fas fa-plus" style="color:#00712D"></i> Create Class</a></li>
        </ul>
    </div>

    <div class="content-wrapper">
        <div class="sidebar" id="sidebar">
            <ul class="sidebar-menu">
                <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Home Page</a></li>
                <li><a asp-controller="Home" asp-action="Teacher"><i class="fas fa-book"></i> Taught Courses</a></li>
                <li><a asp-controller="Home" asp-action="Student"><i class="fas fa-book"></i> Enrolled Courses</a></li>
                <li><a asp-controller="Home" asp-action="Archived"><i class="fas fa-archive"></i> Archived Classes</a></li>
            </ul>
        </div>
    </div>
</header>


<body>
    @RenderBody()
    <script src="~/js/script.js"></script>
</body>
</html>